INSERT INTO product (id,name,image_path,price,description,stock,size,category,period,brand)
VALUES (1, 'ジャケット','images/8751f5b4-52bb-4cd7-8bc6-25fa27d80396_product.id-1.jpg', 15000, 'Made in USA',1,'XL','jacket','70s','levis');
--
--INSERT INTO product (id, name, price, description,stock,size,category,period,bland)
--VALUES (2, 'US.ARMY M-47', 20000, 'アメリカ軍で実際に使用されていたベイカーパンツ',1,'32','pants','40s','US.ARMY');
--
--INSERT INTO product (id, name, price, description,stock,size,category,period,bland)
--VALUES (3, 'シャモアシャツ', 7000, 'L.L.BEAN　80’s',1,'L','shirt','80s','L.L.BEAN');
--
--INSERT INTO product (id, name, price, description,stock,size,category,period,bland)
--VALUES (4, 'ミッキーT', 5000, 'ミッキーのリンガーT',1,'M','T-shirt','90s','no-bland');
--
--INSERT INTO product (id, name, price, description,stock,size,category,period,bland)
--VALUES (5, 'スエードジャケット', 37000, 'ポロカンのスエードジャケット',1,'44','jacket','80s','polocountry');
--
--INSERT INTO product (id, name, price, description,stock,size,category,period,bland)
--VALUES (6, 'ダブルニーダックパンツ', 22000, '70s　カーハートのダブルニー',1,'38','pants','70s','carhart');
--
--INSERT INTO product (id, name, price, description,stock,size,category,period,bland)
--VALUES (7, 'フリース', 15000, 'mont-bellのフリース',1,'L','light outer','regular','montbell');
--
--INSERT INTO product (id, name, price, description,stock,size,category,period,bland)
--VALUES (8, '70s FFAジャケット', 32000, '70s　FFAジャケット　テネシー',1,'42','light outer','70s','FFA');
